// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: sensorproto/sensorproto.proto

package sensorproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorRequest) Reset() {
	*x = SensorRequest{}
	mi := &file_sensorproto_sensorproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorRequest) ProtoMessage() {}

func (x *SensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensorproto_sensorproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorRequest.ProtoReflect.Descriptor instead.
func (*SensorRequest) Descriptor() ([]byte, []int) {
	return file_sensorproto_sensorproto_proto_rawDescGZIP(), []int{0}
}

type SensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	T             string                 `protobuf:"bytes,4,opt,name=t,proto3" json:"t,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorResponse) Reset() {
	*x = SensorResponse{}
	mi := &file_sensorproto_sensorproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorResponse) ProtoMessage() {}

func (x *SensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensorproto_sensorproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorResponse.ProtoReflect.Descriptor instead.
func (*SensorResponse) Descriptor() ([]byte, []int) {
	return file_sensorproto_sensorproto_proto_rawDescGZIP(), []int{1}
}

func (x *SensorResponse) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SensorResponse) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SensorResponse) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *SensorResponse) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

var File_sensorproto_sensorproto_proto protoreflect.FileDescriptor

const file_sensorproto_sensorproto_proto_rawDesc = "" +
	"\n" +
	"\x1dsensorproto/sensorproto.proto\x12\vsensorproto\"\x0f\n" +
	"\rSensorRequest\"H\n" +
	"\x0eSensorResponse\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\x12\f\n" +
	"\x01t\x18\x04 \x01(\tR\x01t2U\n" +
	"\rSensorService\x12D\n" +
	"\tGetSensor\x12\x1a.sensorproto.SensorRequest\x1a\x1b.sensorproto.SensorResponseB\x0fZ\r./sensorprotob\x06proto3"

var (
	file_sensorproto_sensorproto_proto_rawDescOnce sync.Once
	file_sensorproto_sensorproto_proto_rawDescData []byte
)

func file_sensorproto_sensorproto_proto_rawDescGZIP() []byte {
	file_sensorproto_sensorproto_proto_rawDescOnce.Do(func() {
		file_sensorproto_sensorproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensorproto_sensorproto_proto_rawDesc), len(file_sensorproto_sensorproto_proto_rawDesc)))
	})
	return file_sensorproto_sensorproto_proto_rawDescData
}

var file_sensorproto_sensorproto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sensorproto_sensorproto_proto_goTypes = []any{
	(*SensorRequest)(nil),  // 0: sensorproto.SensorRequest
	(*SensorResponse)(nil), // 1: sensorproto.SensorResponse
}
var file_sensorproto_sensorproto_proto_depIdxs = []int32{
	0, // 0: sensorproto.SensorService.GetSensor:input_type -> sensorproto.SensorRequest
	1, // 1: sensorproto.SensorService.GetSensor:output_type -> sensorproto.SensorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sensorproto_sensorproto_proto_init() }
func file_sensorproto_sensorproto_proto_init() {
	if File_sensorproto_sensorproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensorproto_sensorproto_proto_rawDesc), len(file_sensorproto_sensorproto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensorproto_sensorproto_proto_goTypes,
		DependencyIndexes: file_sensorproto_sensorproto_proto_depIdxs,
		MessageInfos:      file_sensorproto_sensorproto_proto_msgTypes,
	}.Build()
	File_sensorproto_sensorproto_proto = out.File
	file_sensorproto_sensorproto_proto_goTypes = nil
	file_sensorproto_sensorproto_proto_depIdxs = nil
}
